name: Publish 🐍🐍 to PyPi
on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install and configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          version: 1.1.11

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Create build
        run: poetry build

      - name: Publish 📦 to PyPi
        if: startsWith(github.ref, 'refs/tags')
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: poetry publish
